server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accountdb
    username: account
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: account-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
